:memo: Updated help page
arctic-hen7/bonnie pull request #1
Opened 2021-04-21 09:49 UTC by Valentine-Mario

updated help page command with a minified version of the docs

2021-04-21 17:59 UTC, Valentine-Mario commented
@arctic-hen7 please review.

2021-04-24 21:35 UTC, arctic-hen7 commented
Hey sorry for the delay! Reviewing now...

2021-04-24 22:00 UTC, arctic-hen7 requested changes
That looks really great, thanks so much! Just a few things with grammar and capitalisation, and I'd prefer the help page be defined in the `BONNIE_HELP_PAGE` constant, meaning only `help_page.rs` needs to be changed.

2021-04-24 22:01 UTC, arctic-hen7 commented
Please note, this is the first pull request I've ever reviewed, so please tell me if there's anything I've done horribly wrong! Also, thanks a lot for the contribution, it means a lot!

2021-04-25 07:50 UTC, Valentine-Mario commented
> Please note, this is the first pull request I've ever reviewed, so please tell me if there's anything I've done horribly wrong! Also, thanks a lot for the contribution, it means a lot!

Lol. The review was great. I highly appreciate the feedback

2021-04-26 21:12 UTC, arctic-hen7 requested changes
Fantastic, thank you very much! Just one '::' rather than ':'!

2021-04-26 21:12 UTC, arctic-hen7 commented on src/help_page.rs
> +    Arguments can be used multiple times in a command::
Typo: two colons rather than one.

2021-04-27 21:15 UTC, arctic-hen7 approved these changes
Looks great, thanks so much!

2021-04-27 21:18 UTC, Valentine-Mario commented
> Looks great, thanks so much!

I'll suggest you add a changelog.md file so that task can be outlined and people get to quickly pick up what to work on.

2021-04-28 05:10 UTC, arctic-hen7 commented
Shall do!

2021-05-02 04:17 UTC, merged