bold keywords in readme
arctic-hen7/bonnie pull request #25
Opened 2022-01-06 01:17 UTC by qpwo

2022-01-06 21:53 UTC, arctic-hen7 requested changes
This looks great, thanks! Just one very minor thing and then we can merge.

2022-01-06 21:53 UTC, arctic-hen7 commented on README.md
> +-   ✨ Supports **interpolating** environment variables
```suggestion
-   ✨ Supports **interpolating environment variables**
```

2022-01-06 23:48 UTC, qpwo commented
Hmm I think I committed the suggestion but it's still saying "1 change requested" but I can't approve it --- anyway of course change it however you'd like it's your repo

2022-01-07 03:55 UTC, arctic-hen7 approved these changes
Yep, I just have to re-review it. And now I have!

2022-01-07 03:56 UTC, merged